name: commands
version: '${project.version}'
main: dev.begi.commands.Commands
api-version: '1.20'
commands:
  kys:
    description: kys lmao
    usage: /kys
  heal:
    description: heals you :0
    usage: /heal
  feed:
    description: feeds you :0
    usage: /feed
  god:
    description: turn ON/OFF God mode
    usage: /god
    aliases:
      - g
